blog/urls.py
from django.urls import path
from blog.views import *

urlpatterns = [
    path('', blog, name='blog' ),
    path('celerytask', test, name='test'),
    path('sendmail', send_mail_to_all, name = 'send mail'),  
] 

demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('blog.urls')),
    path('sendmail/', include('send_mail_app.urls','send_mail_app')),
    path('profile/', include('uprofile.urls')),
    path('inventory/', include('inventory.urls')),
]

if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path('', views.PersonListView.as_view(), name='person_changelist'),
    path('add/', views.PersonCreateView.as_view(), name='person_add'),
    path('<int:pk>/', views.PersonUpdateView.as_view(), name='person_chnage'),
    path('', views.personlist, name='person_changelist'),

    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
]

inventory/models.py
from django.db import models

class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name
    
class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Person(models.Model):
    name = models.CharField(max_length=100)
    birthdate = models.DateField(null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

inventory/forms.py
from django import forms
from django import forms
from . models import Person, City

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('name', 'birthdate', 'country', 'city')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
                try:
                    country_id = int(self.data.get('country'))
                    self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

inventory/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from . models import Person, City
from . forms import PersonForm


# class PersonListView(ListView):
#     model = Person
#     # template_name = 'person_list.html'
#     context_object_name = 'people'


def personlist(request):
    # data = Person.objects.all()
    name = 'Test1'
    data = Person.objects.raw('select * from inventory_person where name=%s', [name])
    # filter(country__startswith='Ne').values('name', 'birthdate','city', 'country',)
    return render(request, 'person_list.html', {'data':data})


class PersonCreateView(CreateView):
    model = Person
    template_name = 'person_add.html'
    form_class = PersonForm
    # fields = ('name', 'birthdate', 'country', 'city')
    success_url = reverse_lazy('person_changelist')

class PersonUpdateView(UpdateView):
    model = Person
    form_class = PersonForm
    # fields = ('name', 'birthdate', 'country', 'city')
    success_url = reverse_lazy('person_changeList')

def load_cities(request):
    country_id = request.GET.get('country')
    cities = City.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'city_dropdown_list_options.html', {'cities': cities})

inventory/templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

inventory/templates/person_add.html
{% extends 'base.html' %}

{% block content %}
<div class='container'
  <h2>Person Form</h2>

  <form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'person_changelist' %}">Nevermind</a>
  </form>
</div>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_country").change(function () {
      var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var countryId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'country': countryId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

{% endblock %}
{% comment %} {% extends 'base.html' %}

{% block content %}
  <h2>Person Form</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'person_changelist' %}">Nevermind</a>
  </form>
{% endblock %} {% endcomment %}

inventory/templates/person_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid mt-3">
    <table>
        <tr>
            <th><b>Name</b></th>
            <th><b>birthdate</b></th>
            <th><b>Country</b></th>
            <th><b>City</b></th>
        </tr>
    {% for i in data %}
        
        <tr>
            <td>{{i.name}}</td>
            <td>{{i.birthdate}}</td>
            <td>{{i.country}} </td> 
            <td>{{i.city}}</td>
        </tr>
    {% endfor %}
    </table>
</div>


{% endblock content %}