blog/urls.py
from django.urls import path
from blog.views import *

urlpatterns = [
    path('', blog, name='blog' ),
    path('celerytask', test, name='test'),
    path('sendmail', send_mail_to_all, name = 'send mail'),  
] 

demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('blog.urls')),
    path('sendmail/', include('send_mail_app.urls','send_mail_app')),
    path('profile/', include('uprofile.urls')),
    path('inventory/', include('inventory.urls')),
]

if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

send_mail_app/urls.py
from django.urls import path
from . views import *

app_name = 'send_mail_app'
# pattern_name = 'demo'


urlpatterns = [
    path('demo/', solo, name='solo'),
    path('upload/', upload, name='upload')
]

send_mail_app/models.py
from django.db import models

class TryDemo(models.Model):
    name = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    number = models.CharField(max_length=13)
    Country = models.CharField(max_length=20)

    def __str__(self):
        return self.name

send_mail_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from . models import TryDemo
from django.contrib import messages
from django.urls import reverse
import io
import csv
from django.core.paginator import Paginator
from .tasks import upload_csv
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from .tasks import upload_csv

def solo(request):
    data = TryDemo.objects.all().order_by('id')
    p = Paginator(data, 15)
    page = request.GET.get('page')
    datas = p.get_page(page)
    context = {'data':data, 'datas':datas}
    if request.htmx:
        return render(request, 'list.html', context)
    return render(request, 'trydemo.html', context)

# def upload(request):
#     upload_csv.delay()
#     return HttpResponse("Work In Progress")
import base64

def upload(request): 
    template = 'trydemo.html'
    context = {
        'order': 'Order of the CSV should be name, city, number, country'
    }
    # print(prompt)
    if request.method == 'POST':
        csv_file=request.FILES['file']
        print(csv_file)
        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'File is not csv type')
            # return HttpResponseRedirect(reverse("send_mail_app:demo"))
            return render(request, template, context)
        csv_file=request.FILES['file'].read()
        byte = base64.b64encode(csv_file)
        data = {
            'csv_file': byte.decode('utf-8'),
            'name':request.FILES['csv_file'].name,
        }
        upload_csv.delay(data=data)
        return HttpResponse("Uploading.....")

    #     data_set = csv_file.read().decode('UTF-8')
    #     io_string = io.StringIO(data_set)
    #     next(io_string)
    #     for column in csv.reader(io_string, delimiter=",", quotechar="|"):
    #         _, created = TryDemo.objects.update_or_create(
    #             name = column[0],
    #             city = column[1],
    #             number = column[2],
    #             Country = column[3],
    #         )
    
    # data = TryDemo.objects.all()
    # context['data'] = data
    # return render(request, 'trydemo.html',context)

send_mail_app/templates/list.html
<ul class="list-group col-4" id="list">
    {% comment %} {% for data in datas %}
    {% if forloop.last and datas.has_next %}
    <div hx-get="{% url 'send_mail_app:solo' %}?page={{datas.number|add:1 }}" hx-trigger="revealed" hx-swap="afterend" hx-target="#list">
    {% else %} {% endcomment %}
    <div>
    {% comment %} {% endif %} {% endcomment %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{data.id}}
            {{data.name}}
            {{data.city}}
            {{data.number}}
            {{data.Country}}
                    
        </li>
    </div>

        
    {% comment %} {% endfor %} {% endcomment %}

</ul>

send_mail_app/templates/trydemo.html
{% extends 'base.html' %}
{% block content %}

{% for message in messages %}
    {{message}}
{% endfor %}
<button onclick="myFunction()">Click me!</button>

    <div class="d-flex align-items-center mt-4">    
        <form action="{% url "send_mail_app:upload" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p><label>Upload a file</label>
            <input type='file' name='file'>
        Only accept csv files
            <button type="submit">Upload</button></p>
        </form>
    </div>
    <div class="align-center col-10 offset-1">
        <div class="d-flex justify-content-between align-items-center">
            <p class="lead ml-0">Data</p>
        </div>
        <hr/>
        
        <div id="contact-list">
            {% include 'list.html' %}
        </div>
    </div>

{% comment %} 
    <div class="d-flex justify-content-between align-items-center">
        <p class="lead ml-0">Data</p>    
    </div>
    <ul class="list-group col-4" id="list">
        
        {% for data n datas %}
        {% if forloop.last %}
        <div hx-get="{% url 'send_mail_app:solo' %}?page={{datas.number|add:1}}" hx-trigger="revealed" hx-swap="afterend" hx-target="#list">
        {% else %}
        <div>
        {% endif %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{data.name}}
                {{data.city}}
                {{data.number}}
                {{data.Country}}
                
            </li>
        </div>
    
        {% endfor %}
    </ul>
    </div> {% endcomment %}
</div>
</div>
<br><br>


{% endblock content %}